# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6792db7c5061b71a910280934e3380f4f3fc56c5508f6790f20382ff1ad3a3de6ea801f84271ebc7bbfa3d372fe00bd510f78071f9bb64c04215f6273baaacf5

test:
  secret_key_base: b378f404d995f4ab9cd7bf3760a372bbeaa9a1d762754c48c1a7673d5ab33150272e10249a99736b66d66414e7afb9c4af99fc5d6f9209bf2c1a1130b324eada

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
